version: '3.8'
services:

  db:
    image: postgres:13.10
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env
    
  backend:
    image: i0ne1y/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/backend
    command: sh -c "sleep 10 && gunicorn foodgram_backend.wsgi:application -b 0.0.0.0:8000 --log-level=debug"
    working_dir: /app/backend

  frontend:
    image: i0ne1y/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.22.1
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/sites-enabled/default
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  static_value:
  media_value:
  db_data:
